version: "2.1"

services:
  docker-microservices:
    extends:
      service: docker-microservices
      file: docker/base-compose.yml

#    depends_on:
#      - init
#      - localstack

#  init:
#    extends:
#      service: init
#      file: docker/dependencies.yml
#
#    depends_on:
#      - localstack

  localstack:
    extends:
      service: localstack
      file: docker/dependencies.yml
