version: "2.1"

services:
  docker-microservices:
    container_name: "docker-microservices"
    build:
      context: baseImage
      dockerfile: Dockerfile
    image: "docker-microservices"
    mem_limit: 1024m
    ports:
      - ${SERVICE_PORT:-48080}:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - AWS_REGION=local
      - AWS_ACCESS_KEY=local
      - AWS_SECRET_ACCESS_KEY=local
      - ENVIRONMENT=local